### ISSUE TITLE
How to solve ''not-resolve-crypto' error

### ISSUE THREAD

**Issue by dydals3440** [AntonioErdeljac/next-auth-v5-advanced-guide#4]
Module not found: Can't resolve 'crypto' in '/Users/kim-yongmin/Desktop/projects/auth-tutorial/node_modules/bcryptjs/dist'

Import trace for requested module:
./node_modules/bcryptjs/dist/bcrypt.js
./auth.config.ts
./auth.ts
./app/api/auth/[...nextauth]/route.ts
./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fauth%2F%5B...nextauth%5D%2Froute&page=%2Fapi%2Fauth%2F%5B...nextauth%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fauth%2F%5B...nextauth%5D%2Froute.ts&appDir=%2FUsers%2Fkim-yongmin%2FDesktop%2Fprojects%2Fauth-tutorial%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2Fkim-yongmin%2FDesktop%2Fprojects%2Fauth-tutorial&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/api/auth/[...nextauth]/route.ts?__next_edge_ssr_entry__

anyone can solve this problem? 
OAuth is not work

**Comment by tatop** [comment]
How did you fix it?
