### ISSUE TITLE
[CRITICAL] Users can keep using app even we delete user's records from database!

### ISSUE THREAD

**Issue by stormi99** [AntonioErdeljac/next-auth-v5-advanced-guide#8]
We are using CredentialsProvider and Prisma to store our users. Everything works great except for 1 problem. If we delete a user from the database (ie. We want to block their access to the app), next-auth doesn't force their session to get logged out. When that user refreshes the page, it lets them get all the way through because it continues to use their JWT cookie token.

Looking through the various next-auth issues, discussions & docs I feel like I'm stuck in an infinite loop. I could not find any solutions and I don't want to use client side logout provider workaround solutions (that is risky for security)

Any solutions ?

**Comment by rslnautic** [comment]
Make a soft-delete and check inside the middleare and the signIn callback .

**Comment by Lodimup** [comment]
you need to delete the session
