### ISSUE TITLE
2FA code being sent before password validation!

### ISSUE THREAD

**Issue by hafisn07** [AntonioErdeljac/next-auth-v5-advanced-guide#9]
When a user with 2FA enabled enters an incorrect password, the 2FA form is displayed prematurely, even though password validation has failed. This results in an "invalid credentials" error after the user enters the 2FA code, causing a confusing user experience and potential security concerns.

**Comment by Mohamed-Abdulla** [comment]
i noticed it too and fixed by comparing password before 2fa

**Comment by hafisn07** [comment]
The issue is fixed by comparing pw and giving proper error message.
see - [fix](https://github.com/hafizn07/next-auth-v5-advanced-guide/commit/3cc7f218b84a49961357f549225d3b11c16a8bc7)
